env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: commonJS
plugins:
  - react
  - "@typescript-eslint"
rules:
  {
    "@typescript-eslint/no-inferrable-types": "off",
    "react/react-in-jsx-scope": "off",
    "react/jsx-filename-extension":
      [1, { "extensions": [".js", ".jsx", ".ts", ".tsx"] }],
  }
